<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Province;
use App\Models\City;

class ProvinceSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            ['code' => '11', 'name' => 'Aceh', 'cities' => [
                ['code' => '01', 'name' => 'Kabupaten Simeulue'],
                ['code' => '02', 'name' => 'Kabupaten Aceh Singkil'],
                ['code' => '03', 'name' => 'Kabupaten Aceh Selatan'],
                ['code' => '04', 'name' => 'Kabupaten Aceh Tenggara'],
                ['code' => '05', 'name' => 'Kabupaten Aceh Timur'],
                ['code' => '06', 'name' => 'Kabupaten Aceh Tengah'],
                ['code' => '07', 'name' => 'Kabupaten Aceh Barat'],
                ['code' => '08', 'name' => 'Kabupaten Aceh Besar'],
                ['code' => '09', 'name' => 'Kabupaten Pidie'],
                ['code' => '10', 'name' => 'Kabupaten Bireuen'],
                ['code' => '11', 'name' => 'Kabupaten Aceh Utara'],
                ['code' => '12', 'name' => 'Kabupaten Aceh Barat Daya'],
                ['code' => '13', 'name' => 'Kabupaten Gayo Lues'],
                ['code' => '14', 'name' => 'Kabupaten Aceh Tamiang'],
                ['code' => '15', 'name' => 'Kabupaten Nagan Raya'],
                ['code' => '16', 'name' => 'Kabupaten Aceh Jaya'],
                ['code' => '17', 'name' => 'Kabupaten Bener Meriah'],
                ['code' => '18', 'name' => 'Kabupaten Pidie Jaya'],
                ['code' => '71', 'name' => 'Kota Banda Aceh'],
                ['code' => '72', 'name' => 'Kota Sabang'],
                ['code' => '73', 'name' => 'Kota Langsa'],
                ['code' => '74', 'name' => 'Kota Lhokseumawe'],
                ['code' => '75', 'name' => 'Kota Subulussalam'],
            ]],
            ['code' => '12', 'name' => 'Sumatera Utara', 'cities' => [
                ['code' => '01', 'name' => 'Kabupaten Nias'],
                ['code' => '02', 'name' => 'Kabupaten Mandailing Natal'],
                ['code' => '03', 'name' => 'Kabupaten Tapanuli Selatan'],
                ['code' => '04', 'name' => 'Kabupaten Tapanuli Tengah'],
                ['code' => '05', 'name' => 'Kabupaten Tapanuli Utara'],
                ['code' => '06', 'name' => 'Kabupaten Toba Samosir'],
                ['code' => '07', 'name' => 'Kabupaten Labuhanbatu'],
                ['code' => '08', 'name' => 'Kabupaten Asahan'],
                ['code' => '09', 'name' => 'Kabupaten Simalungun'],
                ['code' => '10', 'name' => 'Kabupaten Dairi'],
                ['code' => '11', 'name' => 'Kabupaten Karo'],
                ['code' => '12', 'name' => 'Kabupaten Deli Serdang'],
                ['code' => '13', 'name' => 'Kabupaten Langkat'],
                ['code' => '71', 'name' => 'Kota Sibolga'],
                ['code' => '72', 'name' => 'Kota Tanjungbalai'],
                ['code' => '73', 'name' => 'Kota Pematangsiantar'],
                ['code' => '74', 'name' => 'Kota Tebing Tinggi'],
                ['code' => '75', 'name' => 'Kota Medan'],
                ['code' => '76', 'name' => 'Kota Binjai'],
                ['code' => '77', 'name' => 'Kota Padangsidimpuan'],
                ['code' => '78', 'name' => 'Kota Gunungsitoli'],
            ]],
            ['code' => '13', 'name' => 'Sumatera Barat', 'cities' => [
                ['code' => '01', 'name' => 'Kabupaten Kepulauan Mentawai'],
                ['code' => '02', 'name' => 'Kabupaten Pesisir Selatan'],
                ['code' => '03', 'name' => 'Kabupaten Solok'],
                ['code' => '04', 'name' => 'Kabupaten Sijunjung'],
                ['code' => '05', 'name' => 'Kabupaten Tanah Datar'],
                ['code' => '06', 'name' => 'Kabupaten Padang Pariaman'],
                ['code' => '07', 'name' => 'Kabupaten Agam'],
                ['code' => '08', 'name' => 'Kabupaten Lima Puluh Kota'],
                ['code' => '09', 'name' => 'Kabupaten Pasaman'],
                ['code' => '10', 'name' => 'Kabupaten Solok Selatan'],
                ['code' => '11', 'name' => 'Kabupaten Dharmasraya'],
                ['code' => '12', 'name' => 'Kabupaten Pasaman Barat'],
                ['code' => '71', 'name' => 'Kota Padang'],
                ['code' => '72', 'name' => 'Kota Solok'],
                ['code' => '73', 'name' => 'Kota Sawahlunto'],
                ['code' => '74', 'name' => 'Kota Padangpanjang'],
                ['code' => '75', 'name' => 'Kota Bukittinggi'],
                ['code' => '76', 'name' => 'Kota Payakumbuh'],
                ['code' => '77', 'name' => 'Kota Pariaman'],
            ]],
            ['code' => '14', 'name' => 'Riau', 'cities' => [
                ['code' => '01', 'name' => 'Kabupaten Kuantan Singingi'],
                ['code' => '02', 'name' => 'Kabupaten Indragiri Hulu'],
                ['code' => '03', 'name' => 'Kabupaten Indragiri Hilir'],
                ['code' => '04', 'name' => 'Kabupaten Pelalawan'],
                ['code' => '05', 'name' => 'Kabupaten Siak'],
                ['code' => '06', 'name' => 'Kabupaten Kampar'],
                ['code' => '07', 'name' => 'Kabupaten Rokan Hulu'],
                ['code' => '08', 'name' => 'Kabupaten Bengkalis'],
                ['code' => '09', 'name' => 'Kabupaten Rokan Hilir'],
                ['code' => '10', 'name' => 'Kabupaten Kepulauan Meranti'],
                ['code' => '71', 'name' => 'Kota Pekanbaru'],
                ['code' => '72', 'name' => 'Kota Dumai'],
            ]],
            ['code' => '15', 'name' => 'Jambi', 'cities' => [
                ['code' => '01', 'name' => 'Kabupaten Kerinci'],
                ['code' => '02', 'name' => 'Kabupaten Merangin'],
                ['code' => '03', 'name' => 'Kabupaten Sarolangun'],
                ['code' => '04', 'name' => 'Kabupaten Batanghari'],
                ['code' => '05', 'name' => 'Kabupaten Muaro Jambi'],
                ['code' => '06', 'name' => 'Kabupaten Tanjung Jabung Timur'],
                ['code' => '07', 'name' => 'Kabupaten Tanjung Jabung Barat'],
                ['code' => '08', 'name' => 'Kabupaten Tebo'],
                ['code' => '09', 'name' => 'Kabupaten Bungo'],
                ['code' => '71', 'name' => 'Kota Jambi'],
                ['code' => '72', 'name' => 'Kota Sungai Penuh'],
            ]],
            ['code' => '16', 'name' => 'Sumatera Selatan', 'cities' => [
                ['code' => '01', 'name' => 'Kabupaten Ogan Komering Ulu'],
                ['code' => '02', 'name' => 'Kabupaten Ogan Komering Ilir'],
                ['code' => '03', 'name' => 'Kabupaten Muara Enim'],
                ['code' => '04', 'name' => 'Kabupaten Lahat'],
                ['code' => '05', 'name' => 'Kabupaten Musi Rawas'],
                ['code' => '06', 'name' => 'Kabupaten Musi Banyuasin'],
                ['code' => '07', 'name' => 'Kabupaten Banyuasin'],
                ['code' => '71', 'name' => 'Kota Palembang'],
                ['code' => '72', 'name' => 'Kota Prabumulih'],
                ['code' => '73', 'name' => 'Kota Pagaralam'],
                ['code' => '74', 'name' => 'Kota Lubuklinggau'],
            ]],
            ['code' => '17', 'name' => 'Bengkulu', 'cities' => [
                ['code' => '01', 'name' => 'Kabupaten Bengkulu Selatan'],
                ['code' => '02', 'name' => 'Kabupaten Rejang Lebong'],
                ['code' => '03', 'name' => 'Kabupaten Bengkulu Utara'],
                ['code' => '04', 'name' => 'Kabupaten Kaur'],
                ['code' => '05', 'name' => 'Kabupaten Seluma'],
                ['code' => '06', 'name' => 'Kabupaten Mukomuko'],
                ['code' => '07', 'name' => 'Kabupaten Lebong'],
                ['code' => '08', 'name' => 'Kabupaten Kepahiang'],
                ['code' => '09', 'name' => 'Kabupaten Bengkulu Tengah'],
                ['code' => '71', 'name' => 'Kota Bengkulu'],
            ]],
            ['code' => '18', 'name' => 'Lampung', 'cities' => [
                ['code' => '01', 'name' => 'Kabupaten Lampung Barat'],
                ['code' => '02', 'name' => 'Kabupaten Tanggamus'],
                ['code' => '03', 'name' => 'Kabupaten Lampung Selatan'],
                ['code' => '04', 'name' => 'Kabupaten Lampung Timur'],
                ['code' => '05', 'name' => 'Kabupaten Lampung Tengah'],
                ['code' => '06', 'name' => 'Kabupaten Lampung Utara'],
                ['code' => '07', 'name' => 'Kabupaten Way Kanan'],
                ['code' => '08', 'name' => 'Kabupaten Tulang Bawang'],
                ['code' => '09', 'name' => 'Kabupaten Pesawaran'],
                ['code' => '10', 'name' => 'Kabupaten Pringsewu'],
                ['code' => '11', 'name' => 'Kabupaten Mesuji'],
                ['code' => '12', 'name' => 'Kabupaten Tulang Bawang Barat'],
                ['code' => '13', 'name' => 'Kabupaten Pesisir Barat'],
                ['code' => '71', 'name' => 'Kota Bandar Lampung'],
                ['code' => '72', 'name' => 'Kota Metro'],
            ]],
            ['code' => '19', 'name' => 'Kepulauan Bangka Belitung', 'cities' => [
                ['code' => '01', 'name' => 'Kabupaten Bangka'],
                ['code' => '02', 'name' => 'Kabupaten Belitung'],
                ['code' => '03', 'name' => 'Kabupaten Bangka Barat'],
                ['code' => '04', 'name' => 'Kabupaten Bangka Tengah'],
                ['code' => '05', 'name' => 'Kabupaten Bangka Selatan'],
                ['code' => '06', 'name' => 'Kabupaten Belitung Timur'],
                ['code' => '71', 'name' => 'Kota Pangkalpinang'],
            ]],
            ['code' => '21', 'name' => 'Kepulauan Riau', 'cities' => [
                ['code' => '01', 'name' => 'Kabupaten Karimun'],
                ['code' => '02', 'name' => 'Kabupaten Bintan'],
                ['code' => '03', 'name' => 'Kabupaten Natuna'],
                ['code' => '04', 'name' => 'Kabupaten Lingga'],
                ['code' => '05', 'name' => 'Kabupaten Kepulauan Anambas'],
                ['code' => '71', 'name' => 'Kota Batam'],
                ['code' => '72', 'name' => 'Kota Tanjungpinang'],
            ]],
            ['code' => '31', 'name' => 'DKI Jakarta', 'cities' => [
                ['code' => '01', 'name' => 'Kabupaten Kepulauan Seribu'],
                ['code' => '71', 'name' => 'Kota Jakarta Selatan'],
                ['code' => '72', 'name' => 'Kota Jakarta Timur'],
                ['code' => '73', 'name' => 'Kota Jakarta Pusat'],
                ['code' => '74', 'name' => 'Kota Jakarta Barat'],
                ['code' => '75', 'name' => 'Kota Jakarta Utara'],
            ]],
            ['code' => '32', 'name' => 'Jawa Barat', 'cities' => [
                ['code' => '01', 'name' => 'Kabupaten Bogor'],
                ['code' => '02', 'name' => 'Kabupaten Sukabumi'],
                ['code' => '03', 'name' => 'Kabupaten Cianjur'],
                ['code' => '04', 'name' => 'Kabupaten Bandung'],
                ['code' => '05', 'name' => 'Kabupaten Garut'],
                ['code' => '06', 'name' => 'Kabupaten Tasikmalaya'],
                ['code' => '07', 'name' => 'Kabupaten Ciamis'],
                ['code' => '08', 'name' => 'Kabupaten Kuningan'],
                ['code' => '09', 'name' => 'Kabupaten Cirebon'],
                ['code' => '10', 'name' => 'Kabupaten Majalengka'],
                ['code' => '11', 'name' => 'Kabupaten Sumedang'],
                ['code' => '12', 'name' => 'Kabupaten Indramayu'],
                ['code' => '13', 'name' => 'Kabupaten Subang'],
                ['code' => '14', 'name' => 'Kabupaten Purwakarta'],
                ['code' => '15', 'name' => 'Kabupaten Karawang'],
                ['code' => '16', 'name' => 'Kabupaten Bekasi'],
                ['code' => '17', 'name' => 'Kabupaten Bandung Barat'],
                ['code' => '18', 'name' => 'Kabupaten Pangandaran'],
                ['code' => '71', 'name' => 'Kota Bogor'],
                ['code' => '72', 'name' => 'Kota Sukabumi'],
                ['code' => '73', 'name' => 'Kota Bandung'],
                ['code' => '74', 'name' => 'Kota Cirebon'],
                ['code' => '75', 'name' => 'Kota Bekasi'],
                ['code' => '76', 'name' => 'Kota Depok'],
                ['code' => '77', 'name' => 'Kota Cimahi'],
                ['code' => '78', 'name' => 'Kota Tasikmalaya'],
                ['code' => '79', 'name' => 'Kota Banjar'],
            ]],
            ['code' => '33', 'name' => 'Jawa Tengah', 'cities' => [
                ['code' => '01', 'name' => 'Kabupaten Cilacap'],
                ['code' => '02', 'name' => 'Kabupaten Banyumas'],
                ['code' => '03', 'name' => 'Kabupaten Purbalingga'],
                ['code' => '04', 'name' => 'Kabupaten Banjarnegara'],
                ['code' => '05', 'name' => 'Kabupaten Kebumen'],
                ['code' => '06', 'name' => 'Kabupaten Purworejo'],
                ['code' => '07', 'name' => 'Kabupaten Wonosobo'],
                ['code' => '08', 'name' => 'Kabupaten Magelang'],
                ['code' => '09', 'name' => 'Kabupaten Boyolali'],
                ['code' => '10', 'name' => 'Kabupaten Klaten'],
                ['code' => '11', 'name' => 'Kabupaten Sukoharjo'],
                ['code' => '12', 'name' => 'Kabupaten Wonogiri'],
                ['code' => '13', 'name' => 'Kabupaten Karanganyar'],
                ['code' => '14', 'name' => 'Kabupaten Sragen'],
                ['code' => '15', 'name' => 'Kabupaten Grobogan'],
                ['code' => '16', 'name' => 'Kabupaten Blora'],
                ['code' => '17', 'name' => 'Kabupaten Rembang'],
                ['code' => '18', 'name' => 'Kabupaten Pati'],
                ['code' => '19', 'name' => 'Kabupaten Kudus'],
                ['code' => '20', 'name' => 'Kabupaten Jepara'],
                ['code' => '21', 'name' => 'Kabupaten Demak'],
                ['code' => '22', 'name' => 'Kabupaten Semarang'],
                ['code' => '23', 'name' => 'Kabupaten Temanggung'],
                ['code' => '24', 'name' => 'Kabupaten Kendal'],
                ['code' => '25', 'name' => 'Kabupaten Batang'],
                ['code' => '26', 'name' => 'Kabupaten Pekalongan'],
                ['code' => '27', 'name' => 'Kabupaten Pemalang'],
                ['code' => '28', 'name' => 'Kabupaten Tegal'],
                ['code' => '29', 'name' => 'Kabupaten Brebes'],
                ['code' => '71', 'name' => 'Kota Magelang'],
                ['code' => '72', 'name' => 'Kota Surakarta'],
                ['code' => '73', 'name' => 'Kota Salatiga'],
                ['code' => '74', 'name' => 'Kota Semarang'],
                ['code' => '75', 'name' => 'Kota Pekalongan'],
                ['code' => '76', 'name' => 'Kota Tegal'],
            ]],
            ['code' => '34', 'name' => 'DI Yogyakarta', 'cities' => [
                ['code' => '01', 'name' => 'Kabupaten Kulon Progo'],
                ['code' => '02', 'name' => 'Kabupaten Bantul'],
                ['code' => '03', 'name' => 'Kabupaten Gunungkidul'],
                ['code' => '04', 'name' => 'Kabupaten Sleman'],
                ['code' => '71', 'name' => 'Kota Yogyakarta'],
            ]],
            ['code' => '35', 'name' => 'Jawa Timur', 'cities' => [
                ['code' => '01', 'name' => 'Kabupaten Pacitan'],
                ['code' => '02', 'name' => 'Kabupaten Ponorogo'],
                ['code' => '03', 'name' => 'Kabupaten Trenggalek'],
                ['code' => '04', 'name' => 'Kabupaten Tulungagung'],
                ['code' => '05', 'name' => 'Kabupaten Blitar'],
                ['code' => '06', 'name' => 'Kabupaten Kediri'],
                ['code' => '07', 'name' => 'Kabupaten Malang'],
                ['code' => '08', 'name' => 'Kabupaten Lumajang'],
                ['code' => '09', 'name' => 'Kabupaten Jember'],
                ['code' => '10', 'name' => 'Kabupaten Banyuwangi'],
                ['code' => '11', 'name' => 'Kabupaten Bondowoso'],
                ['code' => '12', 'name' => 'Kabupaten Situbondo'],
                ['code' => '13', 'name' => 'Kabupaten Probolinggo'],
                ['code' => '14', 'name' => 'Kabupaten Pasuruan'],
                ['code' => '15', 'name' => 'Kabupaten Sidoarjo'],
                ['code' => '16', 'name' => 'Kabupaten Mojokerto'],
                ['code' => '17', 'name' => 'Kabupaten Jombang'],
                ['code' => '18', 'name' => 'Kabupaten Nganjuk'],
                ['code' => '19', 'name' => 'Kabupaten Madiun'],
                ['code' => '20', 'name' => 'Kabupaten Magetan'],
                ['code' => '21', 'name' => 'Kabupaten Ngawi'],
                ['code' => '22', 'name' => 'Kabupaten Bojonegoro'],
                ['code' => '23', 'name' => 'Kabupaten Tuban'],
                ['code' => '24', 'name' => 'Kabupaten Lamongan'],
                ['code' => '25', 'name' => 'Kabupaten Gresik'],
                ['code' => '26', 'name' => 'Kabupaten Bangkalan'],
                ['code' => '27', 'name' => 'Kabupaten Sampang'],
                ['code' => '28', 'name' => 'Kabupaten Pamekasan'],
                ['code' => '29', 'name' => 'Kabupaten Sumenep'],
                ['code' => '71', 'name' => 'Kota Kediri'],
                ['code' => '72', 'name' => 'Kota Blitar'],
                ['code' => '73', 'name' => 'Kota Malang'],
                ['code' => '74', 'name' => 'Kota Probolinggo'],
                ['code' => '75', 'name' => 'Kota Pasuruan'],
                ['code' => '76', 'name' => 'Kota Mojokerto'],
                ['code' => '77', 'name' => 'Kota Madiun'],
                ['code' => '78', 'name' => 'Kota Surabaya'],
                ['code' => '79', 'name' => 'Kota Batu'],
            ]],
            ['code' => '36', 'name' => 'Banten', 'cities' => [
                ['code' => '01', 'name' => 'Kabupaten Pandeglang'],
                ['code' => '02', 'name' => 'Kabupaten Lebak'],
                ['code' => '03', 'name' => 'Kabupaten Tangerang'],
                ['code' => '04', 'name' => 'Kabupaten Serang'],
                ['code' => '71', 'name' => 'Kota Tangerang'],
                ['code' => '72', 'name' => 'Kota Cilegon'],
                ['code' => '73', 'name' => 'Kota Serang'],
                ['code' => '74', 'name' => 'Kota Tangerang Selatan'],
            ]],
            ['code' => '51', 'name' => 'Bali', 'cities' => [
                ['code' => '01', 'name' => 'Kabupaten Jembrana'],
                ['code' => '02', 'name' => 'Kabupaten Tabanan'],
                ['code' => '03', 'name' => 'Kabupaten Badung'],
                ['code' => '04', 'name' => 'Kabupaten Gianyar'],
                ['code' => '05', 'name' => 'Kabupaten Klungkung'],
                ['code' => '06', 'name' => 'Kabupaten Bangli'],
                ['code' => '07', 'name' => 'Kabupaten Karangasem'],
                ['code' => '08', 'name' => 'Kabupaten Buleleng'],
                ['code' => '71', 'name' => 'Kota Denpasar'],
            ]],
            ['code' => '52', 'name' => 'Nusa Tenggara Barat', 'cities' => [
                ['code' => '01', 'name' => 'Kabupaten Lombok Barat'],
                ['code' => '02', 'name' => 'Kabupaten Lombok Tengah'],
                ['code' => '03', 'name' => 'Kabupaten Lombok Timur'],
                ['code' => '04', 'name' => 'Kabupaten Sumbawa'],
                ['code' => '05', 'name' => 'Kabupaten Dompu'],
                ['code' => '06', 'name' => 'Kabupaten Bima'],
                ['code' => '07', 'name' => 'Kabupaten Sumbawa Barat'],
                ['code' => '08', 'name' => 'Kabupaten Lombok Utara'],
                ['code' => '71', 'name' => 'Kota Mataram'],
                ['code' => '72', 'name' => 'Kota Bima'],
            ]],
            ['code' => '53', 'name' => 'Nusa Tenggara Timur', 'cities' => [
                ['code' => '01', 'name' => 'Kabupaten Sumba Barat'],
                ['code' => '02', 'name' => 'Kabupaten Sumba Timur'],
                ['code' => '03', 'name' => 'Kabupaten Kupang'],
                ['code' => '04', 'name' => 'Kabupaten Timor Tengah Selatan'],
                ['code' => '05', 'name' => 'Kabupaten Timor Tengah Utara'],
                ['code' => '06', 'name' => 'Kabupaten Belu'],
                ['code' => '07', 'name' => 'Kabupaten Alor'],
                ['code' => '08', 'name' => 'Kabupaten Lembata'],
                ['code' => '09', 'name' => 'Kabupaten Flores Timur'],
                ['code' => '10', 'name' => 'Kabupaten Sikka'],
                ['code' => '11', 'name' => 'Kabupaten Ende'],
                ['code' => '12', 'name' => 'Kabupaten Ngada'],
                ['code' => '13', 'name' => 'Kabupaten Manggarai'],
                ['code' => '14', 'name' => 'Kabupaten Rote Ndao'],
                ['code' => '15', 'name' => 'Kabupaten Manggarai Barat'],
                ['code' => '16', 'name' => 'Kabupaten Sumba Tengah'],
                ['code' => '17', 'name' => 'Kabupaten Sumba Barat Daya'],
                ['code' => '18', 'name' => 'Kabupaten Nagekeo'],
                ['code' => '19', 'name' => 'Kabupaten Manggarai Timur'],
                ['code' => '20', 'name' => 'Kabupaten Sabu Raijua'],
                ['code' => '21', 'name' => 'Kabupaten Malaka'],
                ['code' => '71', 'name' => 'Kota Kupang'],
            ]],
            ['code' => '61', 'name' => 'Kalimantan Barat', 'cities' => [
                ['code' => '01', 'name' => 'Kabupaten Sambas'],
                ['code' => '02', 'name' => 'Kabupaten Mempawah'],
                ['code' => '03', 'name' => 'Kabupaten Sanggau'],
                ['code' => '04', 'name' => 'Kabupaten Ketapang'],
                ['code' => '05', 'name' => 'Kabupaten Sintang'],
                ['code' => '06', 'name' => 'Kabupaten Kapuas Hulu'],
                ['code' => '07', 'name' => 'Kabupaten Bengkayang'],
                ['code' => '08', 'name' => 'Kabupaten Landak'],
                ['code' => '09', 'name' => 'Kabupaten Sekadau'],
                ['code' => '10', 'name' => 'Kabupaten Melawi'],
                ['code' => '11', 'name' => 'Kabupaten Kayong Utara'],
                ['code' => '12', 'name' => 'Kabupaten Kubu Raya'],
                ['code' => '71', 'name' => 'Kota Pontianak'],
                ['code' => '72', 'name' => 'Kota Singkawang'],
            ]],
            ['code' => '62', 'name' => 'Kalimantan Tengah', 'cities' => [
                ['code' => '01', 'name' => 'Kabupaten Kotawaringin Barat'],
                ['code' => '02', 'name' => 'Kabupaten Kotawaringin Timur'],
                ['code' => '03', 'name' => 'Kabupaten Kapuas'],
                ['code' => '04', 'name' => 'Kabupaten Barito Selatan'],
                ['code' => '05', 'name' => 'Kabupaten Barito Utara'],
                ['code' => '06', 'name' => 'Kabupaten Sukamara'],
                ['code' => '07', 'name' => 'Kabupaten Lamandau'],
                ['code' => '08', 'name' => 'Kabupaten Seruyan'],
                ['code' => '09', 'name' => 'Kabupaten Katingan'],
                ['code' => '10', 'name' => 'Kabupaten Pulang Pisau'],
                ['code' => '11', 'name' => 'Kabupaten Gunung Mas'],
                ['code' => '12', 'name' => 'Kabupaten Barito Timur'],
                ['code' => '13', 'name' => 'Kabupaten Murung Raya'],
                ['code' => '71', 'name' => 'Kota Palangkaraya'],
            ]],
            ['code' => '63', 'name' => 'Kalimantan Selatan', 'cities' => [
                ['code' => '01', 'name' => 'Kabupaten Tanah Laut'],
                ['code' => '02', 'name' => 'Kabupaten Kota Baru'],
                ['code' => '03', 'name' => 'Kabupaten Banjar'],
                ['code' => '04', 'name' => 'Kabupaten Barito Kuala'],
                ['code' => '05', 'name' => 'Kabupaten Tapin'],
                ['code' => '06', 'name' => 'Kabupaten Hulu Sungai Selatan'],
                ['code' => '07', 'name' => 'Kabupaten Hulu Sungai Tengah'],
                ['code' => '08', 'name' => 'Kabupaten Hulu Sungai Utara'],
                ['code' => '09', 'name' => 'Kabupaten Tabalong'],
                ['code' => '10', 'name' => 'Kabupaten Tanah Bumbu'],
                ['code' => '11', 'name' => 'Kabupaten Balangan'],
                ['code' => '71', 'name' => 'Kota Banjarmasin'],
                ['code' => '72', 'name' => 'Kota Banjarbaru'],
            ]],
            ['code' => '64', 'name' => 'Kalimantan Timur', 'cities' => [
                ['code' => '01', 'name' => 'Kabupaten Paser'],
                ['code' => '02', 'name' => 'Kabupaten Kutai Barat'],
                ['code' => '03', 'name' => 'Kabupaten Kutai Kartanegara'],
                ['code' => '04', 'name' => 'Kabupaten Kutai Timur'],
                ['code' => '05', 'name' => 'Kabupaten Berau'],
                ['code' => '06', 'name' => 'Kabupaten Penajam Paser Utara'],
                ['code' => '07', 'name' => 'Kabupaten Mahakam Ulu'],
                ['code' => '71', 'name' => 'Kota Balikpapan'],
                ['code' => '72', 'name' => 'Kota Samarinda'],
                ['code' => '73', 'name' => 'Kota Bontang'],
            ]],
            ['code' => '65', 'name' => 'Kalimantan Utara', 'cities' => [
                ['code' => '01', 'name' => 'Kabupaten Malinau'],
                ['code' => '02', 'name' => 'Kabupaten Bulungan'],
                ['code' => '03', 'name' => 'Kabupaten Tana Tidung'],
                ['code' => '04', 'name' => 'Kabupaten Nunukan'],
                ['code' => '71', 'name' => 'Kota Tarakan'],
            ]],
            ['code' => '71', 'name' => 'Sulawesi Utara', 'cities' => [
                ['code' => '01', 'name' => 'Kabupaten Bolaang Mongondow'],
                ['code' => '02', 'name' => 'Kabupaten Minahasa'],
                ['code' => '03', 'name' => 'Kabupaten Kepulauan Sangihe'],
                ['code' => '04', 'name' => 'Kabupaten Kepulauan Talaud'],
                ['code' => '05', 'name' => 'Kabupaten Minahasa Selatan'],
                ['code' => '06', 'name' => 'Kabupaten Minahasa Utara'],
                ['code' => '07', 'name' => 'Kabupaten Bolaang Mongondow Utara'],
                ['code' => '08', 'name' => 'Kabupaten Kepulauan Siau Tagulandang Biaro'],
                ['code' => '09', 'name' => 'Kabupaten Minahasa Tenggara'],
                ['code' => '10', 'name' => 'Kabupaten Bolaang Mongondow Selatan'],
                ['code' => '11', 'name' => 'Kabupaten Bolaang Mongondow Timur'],
                ['code' => '71', 'name' => 'Kota Manado'],
                ['code' => '72', 'name' => 'Kota Bitung'],
                ['code' => '73', 'name' => 'Kota Tomohon'],
                ['code' => '74', 'name' => 'Kota Kotamobagu'],
            ]],
            ['code' => '72', 'name' => 'Sulawesi Tengah', 'cities' => [
                ['code' => '01', 'name' => 'Kabupaten Banggai Kepulauan'],
                ['code' => '02', 'name' => 'Kabupaten Banggai'],
                ['code' => '03', 'name' => 'Kabupaten Morowali'],
                ['code' => '04', 'name' => 'Kabupaten Poso'],
                ['code' => '05', 'name' => 'Kabupaten Donggala'],
                ['code' => '06', 'name' => 'Kabupaten Toli-Toli'],
                ['code' => '07', 'name' => 'Kabupaten Buol'],
                ['code' => '08', 'name' => 'Kabupaten Parigi Moutong'],
                ['code' => '09', 'name' => 'Kabupaten Tojo Una-Una'],
                ['code' => '10', 'name' => 'Kabupaten Sigi'],
                ['code' => '11', 'name' => 'Kabupaten Banggai Laut'],
                ['code' => '12', 'name' => 'Kabupaten Morowali Utara'],
                ['code' => '71', 'name' => 'Kota Palu'],
            ]],
            ['code' => '73', 'name' => 'Sulawesi Selatan', 'cities' => [
                ['code' => '01', 'name' => 'Kabupaten Kepulauan Selayar'],
                ['code' => '02', 'name' => 'Kabupaten Bulukumba'],
                ['code' => '03', 'name' => 'Kabupaten Bantaeng'],
                ['code' => '04', 'name' => 'Kabupaten Jeneponto'],
                ['code' => '05', 'name' => 'Kabupaten Takalar'],
                ['code' => '06', 'name' => 'Kabupaten Gowa'],
                ['code' => '07', 'name' => 'Kabupaten Sinjai'],
                ['code' => '08', 'name' => 'Kabupaten Maros'],
                ['code' => '09', 'name' => 'Kabupaten Pangkajene dan Kepulauan'],
                ['code' => '10', 'name' => 'Kabupaten Barru'],
                ['code' => '11', 'name' => 'Kabupaten Bone'],
                ['code' => '12', 'name' => 'Kabupaten Soppeng'],
                ['code' => '13', 'name' => 'Kabupaten Wajo'],
                ['code' => '14', 'name' => 'Kabupaten Sidenreng Rappang'],
                ['code' => '15', 'name' => 'Kabupaten Pinrang'],
                ['code' => '16', 'name' => 'Kabupaten Enrekang'],
                ['code' => '17', 'name' => 'Kabupaten Luwu'],
                ['code' => '18', 'name' => 'Kabupaten Tana Toraja'],
                ['code' => '19', 'name' => 'Kabupaten Luwu Utara'],
                ['code' => '20', 'name' => 'Kabupaten Luwu Timur'],
                ['code' => '21', 'name' => 'Kabupaten Toraja Utara'],
                ['code' => '71', 'name' => 'Kota Makassar'],
                ['code' => '72', 'name' => 'Kota Pare-Pare'],
                ['code' => '73', 'name' => 'Kota Palopo'],
            ]],
            ['code' => '74', 'name' => 'Sulawesi Tenggara', 'cities' => [
                ['code' => '01', 'name' => 'Kabupaten Kolaka'],
                ['code' => '02', 'name' => 'Kabupaten Konawe'],
                ['code' => '03', 'name' => 'Kabupaten Muna'],
                ['code' => '04', 'name' => 'Kabupaten Buton'],
                ['code' => '05', 'name' => 'Kabupaten Konawe Selatan'],
                ['code' => '06', 'name' => 'Kabupaten Bombana'],
                ['code' => '07', 'name' => 'Kabupaten Wakatobi'],
                ['code' => '08', 'name' => 'Kabupaten Kolaka Utara'],
                ['code' => '09', 'name' => 'Kabupaten Buton Utara'],
                ['code' => '10', 'name' => 'Kabupaten Konawe Utara'],
                ['code' => '11', 'name' => 'Kabupaten Kolaka Timur'],
                ['code' => '12', 'name' => 'Kabupaten Konawe Kepulauan'],
                ['code' => '13', 'name' => 'Kabupaten Muna Barat'],
                ['code' => '14', 'name' => 'Kabupaten Buton Tengah'],
                ['code' => '15', 'name' => 'Kabupaten Buton Selatan'],
                ['code' => '71', 'name' => 'Kota Kendari'],
                ['code' => '72', 'name' => 'Kota Bau-Bau'],
            ]],
            ['code' => '75', 'name' => 'Gorontalo', 'cities' => [
                ['code' => '01', 'name' => 'Kabupaten Boalemo'],
                ['code' => '02', 'name' => 'Kabupaten Gorontalo'],
                ['code' => '03', 'name' => 'Kabupaten Pohuwato'],
                ['code' => '04', 'name' => 'Kabupaten Bone Bolango'],
                ['code' => '05', 'name' => 'Kabupaten Gorontalo Utara'],
                ['code' => '71', 'name' => 'Kota Gorontalo'],
            ]],
            ['code' => '76', 'name' => 'Sulawesi Barat', 'cities' => [
                ['code' => '01', 'name' => 'Kabupaten Majene'],
                ['code' => '02', 'name' => 'Kabupaten Polewali Mandar'],
                ['code' => '03', 'name' => 'Kabupaten Mamasa'],
                ['code' => '04', 'name' => 'Kabupaten Mamuju'],
                ['code' => '05', 'name' => 'Kabupaten Mamuju Utara'],
                ['code' => '06', 'name' => 'Kabupaten Mamuju Tengah'],
            ]],
            ['code' => '81', 'name' => 'Maluku', 'cities' => [
                ['code' => '01', 'name' => 'Kabupaten Maluku Tengah'],
                ['code' => '02', 'name' => 'Kabupaten Maluku Tenggara'],
                ['code' => '03', 'name' => 'Kabupaten Maluku Tenggara Barat'],
                ['code' => '04', 'name' => 'Kabupaten Buru'],
                ['code' => '05', 'name' => 'Kabupaten Seram Bagian Timur'],
                ['code' => '06', 'name' => 'Kabupaten Seram Bagian Barat'],
                ['code' => '07', 'name' => 'Kabupaten Kepulauan Aru'],
                ['code' => '08', 'name' => 'Kabupaten Maluku Barat Daya'],
                ['code' => '09', 'name' => 'Kabupaten Buru Selatan'],
                ['code' => '71', 'name' => 'Kota Ambon'],
                ['code' => '72', 'name' => 'Kota Tual'],
            ]],
            ['code' => '82', 'name' => 'Maluku Utara', 'cities' => [
                ['code' => '01', 'name' => 'Kabupaten Halmahera Barat'],
                ['code' => '02', 'name' => 'Kabupaten Halmahera Tengah'],
                ['code' => '03', 'name' => 'Kabupaten Kepulauan Sula'],
                ['code' => '04', 'name' => 'Kabupaten Halmahera Selatan'],
                ['code' => '05', 'name' => 'Kabupaten Halmahera Utara'],
                ['code' => '06', 'name' => 'Kabupaten Halmahera Timur'],
                ['code' => '07', 'name' => 'Kabupaten Pulau Morotai'],
                ['code' => '08', 'name' => 'Kabupaten Pulau Taliabu'],
                ['code' => '71', 'name' => 'Kota Ternate'],
                ['code' => '72', 'name' => 'Kota Tidore Kepulauan'],
            ]],
            ['code' => '91', 'name' => 'Papua Barat', 'cities' => [
                ['code' => '01', 'name' => 'Kabupaten Fakfak'],
                ['code' => '02', 'name' => 'Kabupaten Kaimana'],
                ['code' => '03', 'name' => 'Kabupaten Teluk Wondama'],
                ['code' => '04', 'name' => 'Kabupaten Teluk Bintuni'],
                ['code' => '05', 'name' => 'Kabupaten Manokwari'],
                ['code' => '06', 'name' => 'Kabupaten Sorong Selatan'],
                ['code' => '07', 'name' => 'Kabupaten Sorong'],
                ['code' => '08', 'name' => 'Kabupaten Raja Ampat'],
                ['code' => '09', 'name' => 'Kabupaten Tambrauw'],
                ['code' => '10', 'name' => 'Kabupaten Maybrat'],
                ['code' => '11', 'name' => 'Kabupaten Manokwari Selatan'],
                ['code' => '12', 'name' => 'Kabupaten Pegunungan Arfak'],
                ['code' => '71', 'name' => 'Kota Sorong'],
            ]],
            ['code' => '92', 'name' => 'Papua', 'cities' => [
                ['code' => '01', 'name' => 'Kabupaten Merauke'],
                ['code' => '02', 'name' => 'Kabupaten Jayawijaya'],
                ['code' => '03', 'name' => 'Kabupaten Jayapura'],
                ['code' => '04', 'name' => 'Kabupaten Nabire'],
                ['code' => '08', 'name' => 'Kabupaten Kepulauan Yapen'],
                ['code' => '09', 'name' => 'Kabupaten Biak Numfor'],
                ['code' => '10', 'name' => 'Kabupaten Paniai'],
                ['code' => '11', 'name' => 'Kabupaten Puncak Jaya'],
                ['code' => '12', 'name' => 'Kabupaten Mimika'],
                ['code' => '13', 'name' => 'Kabupaten Boven Digoel'],
                ['code' => '14', 'name' => 'Kabupaten Mappi'],
                ['code' => '15', 'name' => 'Kabupaten Asmat'],
                ['code' => '16', 'name' => 'Kabupaten Yahukimo'],
                ['code' => '17', 'name' => 'Kabupaten Pegunungan Bintang'],
                ['code' => '18', 'name' => 'Kabupaten Tolikara'],
                ['code' => '19', 'name' => 'Kabupaten Sarmi'],
                ['code' => '20', 'name' => 'Kabupaten Keerom'],
                ['code' => '26', 'name' => 'Kabupaten Waropen'],
                ['code' => '27', 'name' => 'Kabupaten Supiori'],
                ['code' => '28', 'name' => 'Kabupaten Mamberamo Raya'],
                ['code' => '29', 'name' => 'Kabupaten Nduga'],
                ['code' => '30', 'name' => 'Kabupaten Lanny Jaya'],
                ['code' => '31', 'name' => 'Kabupaten Mamberamo Tengah'],
                ['code' => '32', 'name' => 'Kabupaten Yalimo'],
                ['code' => '33', 'name' => 'Kabupaten Puncak'],
                ['code' => '34', 'name' => 'Kabupaten Dogiyai'],
                ['code' => '35', 'name' => 'Kabupaten Intan Jaya'],
                ['code' => '36', 'name' => 'Kabupaten Deiyai'],
                ['code' => '71', 'name' => 'Kota Jayapura'],
            ]],
        ];

        foreach ($data as $prov) {
            $province = Province::updateOrCreate(
                ['code' => $prov['code']],
                ['name' => $prov['name']]
            );

            foreach ($prov['cities'] as $city) {
                City::updateOrCreate(
                    ['province_id' => $province->id, 'code' => $city['code']],
                    ['name' => $city['name']]
                );
            }
        }

        $this->command->info('Province & City seeder selesai: ' . Province::count() . ' provinsi, ' . City::count() . ' kota/kabupaten.');
    }
}